name: Build All
on:
  workflow_dispatch:
    inputs:
      kernel_name:
        description: "不输入则使用默认内核名"
        required: false
        default: ''
        type: string
      ace5pro_no_kpm:
        description: "ace5pro不带kpm"
        type: boolean
        default: false
      ace5pro_kpm:
        description: "ace5pro带kpm"
        type: boolean
        default: false

jobs:
  ace5pro_no_kpm:
    if: ${{ inputs.ace5pro_no_kpm == true }}
    uses: ./.github/workflows/ace5pro_no_kpm.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ inputs.kernel_name }}

  ace5pro_kpm:
    if: ${{ inputs.ace5pro_kpm == true }}
    uses: ./.github/workflows/ace5pro_kpm.yml
    secrets: inherit
    with:
      KERNEL_NAME: ${{ inputs.kernel_name }}
